version: "2"
services:
  ldap:
    image: isx46410800/ldapserver19:group
    container_name: ldapserver
    hostname: ldapserver
    ports: 
      - "389:389"
    networks:
     - mynet
  ssh:
    image: isx46410800/ssh19:base
    container_name: ssh
    hostname: ssh
    volumes:
      - "homes:/tmp/home"
    ports:
      - "2022:22"
    networks:
     - mynet
    privileged: true
networks:
  mynet:
volumes:
  homes:
